### PR TITLE
modified spec.yml files in consul and consul-template to systemctl daemon-reload

### LINKED ISSUE #13: consul should be daemon-reload in stead of reload-daemon
In the consul spec .yml file, we should be calling
`systemctl daemon-reload`

instead of `reload-daemon`.

### PR DESCRIPTION
**Pull request by TanyaCouture**
fixes #13

### CODE REVIEW

**Comment by stevendborrelli** [comment]
Thanks! Can you update the iteration to 4?

**Comment by TanyaCouture** [comment]
@stevendborrelli Do you mean add the systemctl daemon-reload command to the other 2 spec.yml files in mantl-packaging/consul?

**Comment by stevendborrelli** [comment]
No, the iteration in the version area in spec.yml needs to be updated from 3 to 4.

**Comment by stevendborrelli** [comment]
https://github.com/asteris-llc/mantl-packaging/blob/master/consul/consul/spec.yml#L5

**Comment by BrianHicks** [comment]
Thanks for the fixes, @TanyaCouture!

**Pull request merged**
