### PR TITLE
Adds Restart directive to traefik.service

### PR DESCRIPTION
**Pull request by sehqlr**
I left #7 hanging for a bit, but here is the fix. What is the best way to test this on a cluster?

### CODE REVIEW

**Comment by BrianHicks** [comment]
The best way to test is to spin up a CentOS instance in vagrant, install the package, then try to break things.

**Comment by BrianHicks** [comment]
Did this ever get tested?

**Comment by sehqlr** [comment]
I guess not 😬. I'm working with vagrant today, so I'll include this on my task list

**Comment by sehqlr** [comment]
I tested this, and it worked. Should be good to merge

**Pull request merged**
